#!/usr/bin/env php
<?php

use ArtARTs36\OpenApiValidator\Console\ValidOpenApiCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

set_time_limit(0);

require __DIR__.'/vendor/autoload.php';

$application = new Application();
$application->add((new ValidOpenApiCommand())->setRootPath(__DIR__));
$application->run(new ArgvInput());
